list.Set( "NPCWeapons", "weapon_fiveseven", "Five Seven" )
list.Set( "NPCWeapons", "weapon_ak47", "AK47" )
list.Set( "NPCWeapons", "weapon_tmp", "TMP" )
list.Set( "NPCWeapons", "weapon_para", "Para" )
list.Set( "NPCWeapons", "weapon_mac10", "Mac10" )
list.Set( "NPCWeapons", "weapon_deagle", "Deagle" )
list.Set( "NPCWeapons", "weapon_pumpshotgun", "Pumpshotgun" )
list.Set( "NPCWeapons", "weapon_mp5", "MP5" )
list.Set( "NPCWeapons", "weapon_m4", "M4" )